One basic property of numpy is that it takes similar datatypes inside its array 

In [1]:
import numpy as np

In [17]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [18]:
a[0]

np.int64(1)

### Numpy VS List

Numpy is more efficient

### Matrix from Scratch

In [14]:
#Matrix
zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
f=np.full((3,3), -127)
f

array([[-127, -127, -127],
       [-127, -127, -127],
       [-127, -127, -127]])

### Random

In [22]:
random=np.random.random((2,3))
print("random array: \n ", random)

random array: 
  [[0.44682776 0.26546923 0.99724807]
 [0.30736186 0.30598316 0.51992916]]


In [23]:
seq=np.arange(0,10,2)
seq

array([0, 2, 4, 6, 8])

### Vector, Matrix and Tensor

In [28]:
vector=np.array([1,2,3])
print("vector : ", vector)

matrix= np.array([[1,2,3],
                [4,5,6]])
print("Matrix : ", matrix)

tensor=np.array([[[1,2], [3,4]],
               [[5,6], [7,8]]])
print("tensor : ", tensor)

vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [29]:
arr =np.array([[1,2,3],
              [4,5,6]])

print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping

In [43]:
arr=np.arange(12)
print("original array :", arr)

reshape=arr.reshape((3,4))
print("reshape array :", reshape)

flattend=reshape.flatten()
print("fllatten array :", flattend)  #it returns the cooy of the array

raveled=reshape.ravel()
print("reveled array :", raveled)  #it returns the view instead of copy

#Transpose
transpose=reshape.T
print("Transpose array :", transpose)

original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
fllatten array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Phase 2 operation on Numpy Array Operations

In [52]:
arr=np.arange(10)
print("Basic Slicing", arr[2:7])

Basic Slicing [2 3 4 5 6]


In [51]:
arr_2d=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Specific element : "  , arr_2d[1,2])
print("Entire row : ", arr_2d[1])
print("Entire Column : ", arr_2d[:, 2])    #new

Specific element :  6
Entire row :  [4 5 6]
Entire Column :  [3 6 9]


In [63]:
unsorted=np.array([1,4,2,7,5,3])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1], [1,2],[2,3]])
print("sorted 2d array by column :", np.sort(arr_2d_unsorted, axis=0)) #top to bottom

Sorted Array [1 2 3 4 5 7]
sorted 2d array by column : [[1 1]
 [2 2]
 [3 3]]


## Filter

In [83]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers % 2 == 0]
print("Even Number : ", even_number)

Even Number :  [ 2  4  6  8 10]


## FIlter with mask

In [84]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [85]:
indices = [0, 2, 4]
print(numbers[indices])

[1 3 5]


In [86]:
where_result=np.where(numbers > 5)
print(where_result)
print("NP where : ", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
NP where :  [ 6  7  8  9 10]


In [87]:
#1:08:36 Chai aur Numpy