One basic property of numpy is that it takes similar datatypes inside its array 

In [1]:
import numpy as np

In [17]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [18]:
a[0]

np.int64(1)

### Numpy VS List

Numpy is more efficient

### Matrix from Scratch

In [14]:
#Matrix
zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
f=np.full((3,3), -127)
f

array([[-127, -127, -127],
       [-127, -127, -127],
       [-127, -127, -127]])

### Random

In [22]:
random=np.random.random((2,3))
print("random array: \n ", random)

random array: 
  [[0.44682776 0.26546923 0.99724807]
 [0.30736186 0.30598316 0.51992916]]


In [23]:
seq=np.arange(0,10,2)
seq

array([0, 2, 4, 6, 8])

### Vector, Matrix and Tensor

In [28]:
vector=np.array([1,2,3])
print("vector : ", vector)

matrix= np.array([[1,2,3],
                [4,5,6]])
print("Matrix : ", matrix)

tensor=np.array([[[1,2], [3,4]],
               [[5,6], [7,8]]])
print("tensor : ", tensor)

vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [29]:
arr =np.array([[1,2,3],
              [4,5,6]])

print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping

In [43]:
arr=np.arange(12)
print("original array :", arr)

reshape=arr.reshape((3,4))
print("reshape array :", reshape)

flattend=reshape.flatten()
print("fllatten array :", flattend)  #it returns the cooy of the array

raveled=reshape.ravel()
print("reveled array :", raveled)  #it returns the view instead of copy

#Transpose
transpose=reshape.T
print("Transpose array :", transpose)

original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
fllatten array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
